import React from "react";

const TuesdayTeachingService = () => {
  return (<div><h2 style={{color:"#DBA514"}}>Tuesday Teaching Service</h2><br /><br /><React.Fragment><p>The message should arise naturally from the Biblical text.
This is probably one of the most fundamental disciplines that need to be addressed. Beware of messages that are based on opinion or personal revelation. Our responsibility is to organize all of the information and be able to clearly identify and communicate the key point of the passage.
It is well organized, easy to follow, with one clearly communicated main point.
You may not necessarily have to limit it to one main point, but the idea here is to leave your audience wanting more after the sermon rather than feeling overwhelmed.</p>
<p>The sermon efficiently uses storytelling and analogies to emphasize the main point.
Stories are useful to paint relevant images in the mind of your audience and help them relate to the point you are making. Jesus spoke in parables that were relevant to the listeners at the time so they would have the opportunity to understand what he is referring to.
Meets the/a need of the congregation.
You are reading this article because you want your sermons to have some type of impact on someone’s life.
Motivates hearers to take action.
Having a call to action at the end of the sermon is a simple way to help your listeners remember what they learned. By applying the lesson throughout the week, the hope is that the message will have a long-term effect helps them grow closer to God.</p>
<p>How do you decide what to preach on?
There’s a lot of information and key points in the Bible that you could preach on. The question is, how do you go about deciding what to preach about? And not only that, but you have to preach next week and the following week for as long as you are preaching. This could be a daunting task, but there are many creative ways to purposefully plan what your sermon themes will be. First off, there’s no right or wrong way to decide what your next sermon will be about. Secondly, you are not alone in making this decision, there are 3 perspectives you should consider before making this decision. The first perspective is from God, take time to hear from Him about what He would like your congregation to hear. God knows exactly what sermon would impact your hearers, so consult with Him before jumping in. The second perspective is from your congregation. Good shepherds, like Jesus, know the needs of their flock and what issues need to be addressed. This can also be instilled from God. He has a way of making it apparent that you should preach about something specific or regarding a specific event, perhaps. The third perspective comes from your personal walk with God. When you are walking closely with God, He will bring things to your attention through your relationship with Him. If you are struggling with something, it’s very likely that other people could be struggling with something similar, as well. Ultimately, the best way to decide what to preach on is to hear from God, He puts things on our hearts to preach about if we take the time to listen. Then we have to do our part by being obedient to what He puts on our hearts.</p>

<p>How do you build a sermon outline?
Once you’ve understood what a great sermon consists of, you’ve heard from God what you should preach on, now all you need to do is put it all together. Great! Where do you start?</p>

  <p>When you think about a basic sermon outline, think about a well-written article: you have an Introduction, a Main Point, the Body, and a Conclusion. Now, simply imagine doing the same with the Bible as your reference. First, produce your attention-grabbing introductory paragraph. This could consist of a personal story, analogy, current event, etc. that relates to the main point of your sermon and brings in a visual element. Then state the main point that you are wanting to make and why it’s important or relevant. What problems arise with this topic? Why is this topic a problem? How do you resolve those problems? The body paragraphs should be built with Scriptures, stories, analogies, questions, and anything that would support the main point. Finally, recap all of your points in the conclusion and refer back to the main point while providing a call-to-action element. A good practice is finding a way to end your sermon by challenging your hearers to apply the main point you just talked about. You want them to continue thinking about the message long after the service is over.</p></React.Fragment></div>)
};

export default TuesdayTeachingService;
